### ISSUE TITLE
Play Command Search

### ISSUE THREAD

**Issue by Hitogoroshii** [ywssp/Bot.wssp#11]
The play command is not searching all of the args for example "!play Can i be him"
the comman only search "Can" and din't include all args in the search
is this a bug? but everything is working fine

**Comment by Hitogoroshii** [comment]
and if i use the youtube video link it will give me the result of the song i want to search

**Comment by ywssp** [comment]
Working on it!

**Comment by ywssp** [comment]
Done! The command now matches the content
