### ISSUE TITLE
ReferenceError: query is not defined

### ISSUE THREAD

**Issue by Hitogoroshii** [ywssp/Bot.wssp#13]
Tried playing a playlist and this pops up is this a Work in progress or a bug?

**Comment by ywssp** [comment]
Done! The command now gets the playlist using `args.searchTerm (the link given)` instead of using `query (undefined)`

Bugged code: 
```
const playlist = await youtube .getPlaylist(query)
```
Fixed code: 
```
const playlist = await youtube .getPlaylist(args.searchTerm)
```

**Comment by Hitogoroshii** [comment]
Thank you!
