### ISSUE TITLE
Play Command

### ISSUE THREAD

**Issue by Hitogoroshii** [ywssp/Bot.wssp#17]
i think choosing a song early will cause a crash when reaction is not finished

**Comment by ywssp** [comment]
Yep, it crashes. Looking for the reason why it crashes atm!

**Comment by ywssp** [comment]
Try to update ytdl-core and see if its fixed

**Comment by ywssp** [comment]
I'm still checking if updating `ytdl-core` fixes the bug

**Comment by Hitogoroshii** [comment]
i think updating ytdl-core fixes the bug but still its an error when the message is deleted after reacting
and thank you for responding fast

**Comment by ywssp** [comment]
> i think updating ytdl-core fixes the bug but still its an error when the message is deleted after reacting
> and thank you for responding fast

Thanks for checking! The terminal of my project in glitch.com doesn't open so i can't check if updating ytdl-core fixes the bug
