### ISSUE TITLE
Queue not Displaying

### ISSUE THREAD

**Issue by Red-King-Sureiya** [ywssp/Bot.wssp#9]
When i have 1 song in queue and used the queue command it says no songs i dont know if this is on purpose but when there is 2 songs in queue and i used the queue command it doesnt send any messages or the queue but there is no error popping up in the console

**Comment by ywssp** [comment]
Don't worry! I'm now looking for bugs on the command

**Comment by ywssp** [comment]
The bug is fixed! The problem was when the command calculates the embeds to send (Embeds have a limit of 25 fields), it does `Math.floor()` instead of `Math.ceil()` and because the queue has less than 25 songs, the sections created are 0 instead of 1

Bugged code:
```
let sections = Math.floor(fieldArray.length / 25);
```

Fixed code:
```
let sections = Math.ceil(fieldArray.length / 25);
```

**Comment by Red-King-Sureiya** [comment]
Thank you very much!
